name: SentinelCI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: pip install -r app/requirements.txt pip-audit

    - name: Run Tests
      run: |
        cd app
        pytest

    - name: Dependency Scan
      run: pip-audit

    - name: Build Docker Image
      run: docker build -t sentinelci .

    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
            image-ref: 'sentinelci'
            format: 'table'
            output: 'trivy-report.txt'
            vuln-type: library
            severity: HIGH,CRITICAL
            ignore-unfixed: true
    - name: Show Trivy Report
      run: cat trivy-report.txt
    - name: Scan Docker Image
      run: trivy image sentinelci > trivy-report.txt

    - name: Generate Security Report
      run: python report.py

    - name: Show Report
      run: cat final-report.txt

    